from .village_roads import SceneVillageRoadMixin
from .village_house_parts import SceneVillageHousePartsMixin
from .village_house_variants import SceneVillageHouseVariantMixin
from .village_props import SceneVillagePropMixin
from .village_settlement import SceneVillageSettlementMixin
from .village_bridge import SceneVillageBridgeMixin


class SceneVillageMixin(SceneVillageRoadMixin, SceneVillageHousePartsMixin, SceneVillageHouseVariantMixin, SceneVillagePropMixin, SceneVillageSettlementMixin, SceneVillageBridgeMixin):
    pass
